### ISSUE TITLE
the webpage is always blank

### ISSUE THREAD

**Issue by Yu1993Yu** [OpenProtein/openprotein#23]
Thanks for your working on this project and great sharing code, there are some problems with me when I run the code.
I just git clone and run the command as:
`python3 __main__.py`
but the errors appeared like this:(I just copy all of them from my terminal, so maybe the format is strange):

`/usr/local/lib/python3.7/site-packages/Bio/PDB/Vector.py:42: BiopythonDeprecationWarning: The module Bio.PDB.Vector has been deprecated in favor of new module Bio.PDB.vectors to solve a name collision with the class Vector. For the class Vector, and vector functions like calc_angle, import from Bio.PDB instead.
  "import from Bio.PDB instead.", BiopythonDeprecationWarning)
------------------------
--- OpenProtein v0.1 ---
------------------------
Starting pre-processing of raw data...
['data/raw/sample.txt']
Preprocessed file for sample.txt already exists.
Skipping pre-processing for this file...
Completed pre-processing.
 * Serving Flask app "dashboard" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/AlexYU/Desktop/openprotein/dashboard.py", line 37, in run
    app.run(debug=False, host='0.0.0.0')
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 990, in run_simple
    inner()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 943, in inner
    fd=fd,
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 786, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 679, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use

2019-05-06 15:39:05: Embed time: 0.00033283233642578125
Traceback (most recent call last):
  File "__main__.py", line 67, in <module>
    minimum_updates=args.minimum_updates)
  File "/Users/AlexYU/Desktop/openprotein/training.py", line 38, in train_model
    loss = model.compute_loss(training_minibatch)
  File "/Users/AlexYU/Desktop/openprotein/openprotein.py", line 45, in compute_loss
    emissions, backbone_atoms_padded, batch_sizes = self._get_network_emissions(original_aa_string)
  File "/Users/AlexYU/Desktop/openprotein/models.py", line 49, in _get_network_emissions
    (data, bi_lstm_batches), self.hidden_layer = self.bi_lstm(packed_input_sequences, self.hidden_layer)
ValueError: too many values to unpack (expected 2)`

the webpage opened after the errors, unfortunately its blank, just like this:
 
![image](https://user-images.githubusercontent.com/38175266/57212563-b3d23500-7016-11e9-8374-5fcf1c3ed05a.png)

By the way, my environment:

- python3.7

- pytorch 1.1

- node 10.15

- macOS Mojave

I just want have test with the code on my computer, what should I do to fix the problems? Any help would be greatly appreciated.
Thanks for the great working again.

**Comment by JeppeHallgren** [comment]
Hey @Yu1993Yu , I believe this is the same issue as https://github.com/OpenProtein/openprotein/issues/26 , which should now be fixed if you pull the latest master. Thanks!

**Comment by Yu1993Yu** [comment]
> Hey @Yu1993Yu , I believe this is the same issue as #26 , which should now be fixed if you pull the latest master. Thanks!

Great! Its simply fix it by clone again！A lot of thanks for you,Sir. Wish u have a good day!

**Comment by JeppeHallgren** [comment]
Great!
